#include "Shared/WebGPU/WebGPUImageCopyBuffer.cpp"
#include "Shared/WebGPU/WebGPUImageCopyExternalImage.cpp"
#include "Shared/WebGPU/WebGPUImageCopyTexture.cpp"
#include "Shared/WebGPU/WebGPUImageCopyTextureTagged.cpp"
#include "Shared/WebGPU/WebGPUImageDataLayout.cpp"
#include "Shared/WebGPU/WebGPUInternalError.cpp"
#include "Shared/WebGPU/WebGPUMultisampleState.cpp"
#include "Shared/WebGPU/WebGPUObjectDescriptorBase.cpp"
