#include "Shared/WebGPU/WebGPUCanvasConfiguration.cpp"
#include "Shared/WebGPU/WebGPUColor.cpp"
#include "Shared/WebGPU/WebGPUColorTargetState.cpp"
#include "Shared/WebGPU/WebGPUCommandBufferDescriptor.cpp"
#include "Shared/WebGPU/WebGPUCommandEncoderDescriptor.cpp"
#include "Shared/WebGPU/WebGPUCompilationMessage.cpp"
#include "Shared/WebGPU/WebGPUComputePassDescriptor.cpp"
#include "Shared/WebGPU/WebGPUComputePassTimestampWrites.cpp"
