#include "Shared/WebGPU/WebGPUQuerySetDescriptor.cpp"
#include "Shared/WebGPU/WebGPURenderBundleDescriptor.cpp"
#include "Shared/WebGPU/WebGPURenderBundleEncoderDescriptor.cpp"
#include "Shared/WebGPU/WebGPURenderPassColorAttachment.cpp"
#include "Shared/WebGPU/WebGPURenderPassDepthStencilAttachment.cpp"
#include "Shared/WebGPU/WebGPURenderPassDescriptor.cpp"
#include "Shared/WebGPU/WebGPURenderPassLayout.cpp"
#include "Shared/WebGPU/WebGPURenderPassTimestampWrites.cpp"
