#include "UIProcess/WebsiteData/WebDeviceOrientationAndMotionAccessController.cpp"
#include "UIProcess/WebsiteData/WebsiteDataRecord.cpp"
#include "UIProcess/WebsiteData/WebsiteDataStore.cpp"
#include "UIProcess/WebsiteData/WebsiteDataStoreConfiguration.cpp"
#include "UIProcess/XR/PlatformXRSystem.cpp"
