#include "GPUProcess/media/RemoteLegacyCDMProxy.cpp"
#include "GPUProcess/media/RemoteLegacyCDMSessionProxy.cpp"
#include "GPUProcess/media/RemoteMediaEngineConfigurationFactoryProxy.cpp"
#include "GPUProcess/media/RemoteMediaPlayerManagerProxy.cpp"
#include "GPUProcess/media/RemoteMediaPlayerProxy.cpp"
#include "GPUProcess/media/RemoteMediaResource.cpp"
#include "GPUProcess/media/RemoteMediaResourceLoader.cpp"
#include "GPUProcess/media/RemoteMediaResourceManager.cpp"
