#include "RemoteGPUProxyMessageReceiver.cpp"
#include "RemoteGraphicsContextGLMessageReceiver.cpp"
#include "RemoteGraphicsContextGLProxyMessageReceiver.cpp"
#include "RemoteGraphicsContextMessageReceiver.cpp"
#include "RemotePipelineLayoutMessageReceiver.cpp"
#include "RemotePresentationContextMessageReceiver.cpp"
#include "RemoteQuerySetMessageReceiver.cpp"
#include "RemoteQueueMessageReceiver.cpp"
