// Automatically generated from C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/runtime/DatePrototype.cpp using C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static constinit const struct CompactHashIndex datePrototypeTableIndex[133] = {
    { 41, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { 29, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, 129 },
    { 24, -1 },
    { 10, 132 },
    { -1, -1 },
    { 19, 130 },
    { -1, -1 },
    { 1, -1 },
    { -1, -1 },
    { 25, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 26, -1 },
    { -1, -1 },
    { 33, -1 },
    { -1, -1 },
    { 35, -1 },
    { 9, 128 },
    { 22, -1 },
    { -1, -1 },
    { 16, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 23, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { -1, -1 },
    { 15, -1 },
    { 38, -1 },
    { -1, -1 },
    { -1, -1 },
    { 18, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, -1 },
    { -1, -1 },
    { -1, -1 },
    { 28, -1 },
    { -1, -1 },
    { 32, -1 },
    { -1, -1 },
    { -1, -1 },
    { 8, -1 },
    { 42, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 36, -1 },
    { 27, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 20, -1 },
    { 13, 131 },
    { 7, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 43, -1 },
    { -1, -1 },
    { -1, -1 },
    { 39, -1 },
    { -1, -1 },
    { 40, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 21, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { 30, -1 },
    { 31, -1 },
    { 34, -1 },
    { 37, -1 },
};

static constinit const struct HashTableValue datePrototypeTableValues[44] = {
   { "toString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToString, 0 } },
   { "toISOString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToISOString, 0 } },
   { "toDateString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToDateString, 0 } },
   { "toTimeString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToTimeString, 0 } },
   { "toLocaleString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToLocaleString, 0 } },
   { "toLocaleDateString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToLocaleDateString, 0 } },
   { "toLocaleTimeString"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToLocaleTimeString, 0 } },
   { "valueOf"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetTimeIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetTime, 0 } },
   { "getTime"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetTimeIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetTime, 0 } },
   { "getFullYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetFullYearIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetFullYear, 0 } },
   { "getUTCFullYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCFullYearIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCFullYear, 0 } },
   { "getMonth"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetMonthIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetMonth, 0 } },
   { "getUTCMonth"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCMonthIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCMonth, 0 } },
   { "getDate"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetDateIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetDate, 0 } },
   { "getUTCDate"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCDateIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCDate, 0 } },
   { "getDay"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetDayIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetDay, 0 } },
   { "getUTCDay"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCDayIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCDay, 0 } },
   { "getHours"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetHoursIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetHours, 0 } },
   { "getUTCHours"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCHoursIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCHours, 0 } },
   { "getMinutes"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetMinutesIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetMinutes, 0 } },
   { "getUTCMinutes"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCMinutesIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCMinutes, 0 } },
   { "getSeconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetSecondsIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetSeconds, 0 } },
   { "getUTCSeconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCSecondsIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCSeconds, 0 } },
   { "getMilliseconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetMillisecondsIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetMilliSeconds, 0 } },
   { "getUTCMilliseconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetUTCMillisecondsIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetUTCMilliseconds, 0 } },
   { "getTimezoneOffset"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetTimezoneOffsetIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetTimezoneOffset, 0 } },
   { "getYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeGetYearIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncGetYear, 0 } },
   { "setTime"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DatePrototypeSetTimeIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetTime, 1 } },
   { "setMilliseconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetMilliSeconds, 1 } },
   { "setUTCMilliseconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCMilliseconds, 1 } },
   { "setSeconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetSeconds, 2 } },
   { "setUTCSeconds"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCSeconds, 2 } },
   { "setMinutes"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetMinutes, 3 } },
   { "setUTCMinutes"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCMinutes, 3 } },
   { "setHours"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetHours, 4 } },
   { "setUTCHours"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCHours, 4 } },
   { "setDate"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetDate, 1 } },
   { "setUTCDate"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCDate, 1 } },
   { "setMonth"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetMonth, 2 } },
   { "setUTCMonth"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCMonth, 2 } },
   { "setFullYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetFullYear, 3 } },
   { "setUTCFullYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetUTCFullYear, 3 } },
   { "setYear"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncSetYear, 1 } },
   { "toJSON"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dateProtoFuncToJSON, 1 } },
};

static constinit const struct HashTable datePrototypeTable =
    { 44, 127, false, nullptr, datePrototypeTableValues, datePrototypeTableIndex };

} // namespace JSC
