// Automatically generated from C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/runtime/JSDataViewPrototype.cpp using C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static constinit const struct CompactHashIndex dataViewTableIndex[70] = {
    { -1, -1 },
    { -1, -1 },
    { 23, -1 },
    { 9, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 13, 69 },
    { -1, -1 },
    { 22, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 21, -1 },
    { -1, -1 },
    { 0, 67 },
    { -1, -1 },
    { 1, 68 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 7, -1 },
    { -1, -1 },
    { -1, -1 },
    { 10, 66 },
    { 2, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { -1, -1 },
    { 5, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 15, -1 },
    { 3, 65 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { 8, -1 },
    { 11, -1 },
    { 16, -1 },
    { 18, -1 },
    { 19, -1 },
    { 20, -1 },
};

static constinit const struct HashTableValue dataViewTableValues[24] = {
   { "getInt8"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetInt8, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetInt8, 1 } },
   { "getUint8"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetUint8, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetUint8, 1 } },
   { "getInt16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetInt16, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetInt16, 1 } },
   { "getUint16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetUint16, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetUint16, 1 } },
   { "getInt32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetInt32, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetInt32, 1 } },
   { "getUint32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetUint32, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetUint32, 1 } },
   { "getFloat16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetFloat16, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetFloat16, 1 } },
   { "getFloat32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetFloat32, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetFloat32, 1 } },
   { "getFloat64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewGetFloat64, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetFloat64, 1 } },
   { "getBigInt64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetBigInt64, 1 } },
   { "getBigUint64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dataViewProtoFuncGetBigUint64, 1 } },
   { "setInt8"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetInt8, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetInt8, 2 } },
   { "setUint8"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetUint8, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetUint8, 2 } },
   { "setInt16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetInt16, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetInt16, 2 } },
   { "setUint16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetUint16, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetUint16, 2 } },
   { "setInt32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetInt32, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetInt32, 2 } },
   { "setUint32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetUint32, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetUint32, 2 } },
   { "setFloat16"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetFloat16, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetFloat16, 2 } },
   { "setFloat32"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetFloat32, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetFloat32, 2 } },
   { "setFloat64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), DataViewSetFloat64, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetFloat64, 2 } },
   { "setBigInt64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetBigInt64, 2 } },
   { "setBigUint64"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, dataViewProtoFuncSetBigUint64, 2 } },
   { "buffer"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { HashTableValue::GetterSetterType, dataViewProtoGetterBuffer, 0 } },
   { "byteOffset"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ReadOnly|PropertyAttribute::CustomAccessor), NoIntrinsic, { HashTableValue::GetterSetterType, dataViewProtoGetterByteOffset, 0 } },
};

static constinit const struct HashTable dataViewTable =
    { 24, 63, true, nullptr, dataViewTableValues, dataViewTableIndex };

} // namespace JSC
