// Automatically generated from C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/runtime/ObjectConstructor.cpp using C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "JSCBuiltins.h"
#include "Lookup.h"

namespace JSC {

static constinit const struct CompactHashIndex objectConstructorTableIndex[67] = {
    { 1, 66 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 16, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 13, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 20, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { 8, -1 },
    { 19, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, -1 },
    { 15, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, 65 },
    { -1, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 9, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { 14, -1 },
    { 7, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { 6, -1 },
    { 18, -1 },
};

static constinit const struct HashTableValue objectConstructorTableValues[21] = {
   { "getPrototypeOf"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectGetPrototypeOfIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorGetPrototypeOf, 1 } },
   { "setPrototypeOf"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorSetPrototypeOf, 2 } },
   { "getOwnPropertyDescriptor"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorGetOwnPropertyDescriptor, 2 } },
   { "getOwnPropertyDescriptors"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorGetOwnPropertyDescriptors, 1 } },
   { "getOwnPropertyNames"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectGetOwnPropertyNamesIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorGetOwnPropertyNames, 1 } },
   { "getOwnPropertySymbols"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectGetOwnPropertySymbolsIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorGetOwnPropertySymbols, 1 } },
   { "keys"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectKeysIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorKeys, 1 } },
   { "defineProperty"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorDefineProperty, 3 } },
   { "defineProperties"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorDefineProperties, 2 } },
   { "create"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectCreateIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorCreate, 2 } },
   { "seal"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorSeal, 1 } },
   { "freeze"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorFreeze, 1 } },
   { "preventExtensions"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorPreventExtensions, 1 } },
   { "isSealed"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorIsSealed, 1 } },
   { "isFrozen"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorIsFrozen, 1 } },
   { "isExtensible"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorIsExtensible, 1 } },
   { "is"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectIsIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorIs, 2 } },
   { "assign"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectAssignIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorAssign, 2 } },
   { "values"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorValues, 1 } },
   { "entries"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, objectConstructorEntries, 1 } },
   { "fromEntries"_s, ((static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function)) & ~PropertyAttribute::Function) | PropertyAttribute::Builtin, NoIntrinsic, { HashTableValue::BuiltinGeneratorType, objectConstructorFromEntriesCodeGenerator, 1 } },
};

static constinit const struct HashTable objectConstructorTable =
    { 21, 63, false, nullptr, objectConstructorTableValues, objectConstructorTableIndex };

} // namespace JSC
