// Automatically generated from C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/runtime/RegExpConstructor.cpp using C:/Users/Admin/source/repos/!OpenCode/Apotheosis/WebKit/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static constinit const struct CompactHashIndex regExpConstructorTableIndex[65] = {
    { -1, -1 },
    { 8, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { 7, -1 },
    { 2, -1 },
    { 9, -1 },
    { 16, -1 },
    { -1, -1 },
    { -1, -1 },
    { 19, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { -1, -1 },
    { 15, -1 },
    { -1, -1 },
    { 0, -1 },
    { -1, -1 },
    { 18, -1 },
    { 20, -1 },
    { 13, -1 },
};

static constinit const struct HashTableValue regExpConstructorTableValues[21] = {
   { "input"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorInput, setRegExpConstructorInput } },
   { "$_"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorInput, setRegExpConstructorInput } },
   { "multiline"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorMultiline, setRegExpConstructorMultiline } },
   { "$*"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorMultiline, setRegExpConstructorMultiline } },
   { "lastMatch"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLastMatch, 0 } },
   { "$&"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLastMatch, 0 } },
   { "lastParen"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLastParen, 0 } },
   { "$+"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLastParen, 0 } },
   { "leftContext"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLeftContext, 0 } },
   { "$`"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorLeftContext, 0 } },
   { "rightContext"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorRightContext, 0 } },
   { "$'"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorRightContext, 0 } },
   { "$1"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$2"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$3"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$4"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$5"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$6"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$7"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$8"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
   { "$9"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { HashTableValue::GetterSetterType, regExpConstructorDollar, 0 } },
};

static constinit const struct HashTable regExpConstructorTable =
    { 21, 63, true, nullptr, regExpConstructorTableValues, regExpConstructorTableIndex };

} // namespace JSC
