#include "runtime/VMEntryScope.cpp"
#include "runtime/VMManager.cpp"
#include "runtime/VMTraps.cpp"
#include "runtime/VarOffset.cpp"
#include "runtime/WaiterListManager.cpp"
#include "runtime/Watchdog.cpp"
#include "runtime/WeakMapConstructor.cpp"
#include "runtime/WeakMapImpl.cpp"
