#include "wasm/js/WebAssemblyGlobalPrototype.cpp"
#include "wasm/js/WebAssemblyInstanceConstructor.cpp"
#include "wasm/js/WebAssemblyInstancePrototype.cpp"
#include "wasm/js/WebAssemblyLinkErrorConstructor.cpp"
#include "wasm/js/WebAssemblyLinkErrorPrototype.cpp"
#include "wasm/js/WebAssemblyMemoryConstructor.cpp"
#include "wasm/js/WebAssemblyMemoryPrototype.cpp"
#include "wasm/js/WebAssemblyModuleConstructor.cpp"
