#include "runtime/NumberPredictionFuzzerAgent.cpp"
#include "runtime/NumberPrototype.cpp"
#include "runtime/ObjectConstructor.cpp"
#include "runtime/ObjectInitializationScope.cpp"
#include "runtime/ObjectPrototype.cpp"
#include "runtime/Operations.cpp"
#include "runtime/Options.cpp"
#include "runtime/OrderedHashTable.cpp"
