#include "ftl/FTLLocation.cpp"
#include "ftl/FTLOSREntry.cpp"
#include "ftl/FTLOSRExit.cpp"
#include "ftl/FTLOSRExitCompiler.cpp"
#include "ftl/FTLOSRExitHandle.cpp"
#include "ftl/FTLOperations.cpp"
#include "ftl/FTLOutput.cpp"
#include "ftl/FTLPatchpointExceptionHandle.cpp"
