#include "b3/B3DataSection.cpp"
#include "b3/B3DuplicateTails.cpp"
#include "b3/B3Effects.cpp"
#include "b3/B3EliminateCommonSubexpressions.cpp"
#include "b3/B3EliminateDeadCode.cpp"
#include "b3/B3EnsureLoopPreHeaders.cpp"
#include "b3/B3EstimateStaticExecutionCounts.cpp"
#include "b3/B3ExtractValue.cpp"
