#include "ftl/FTLExitTimeObjectMaterialization.cpp"
#include "ftl/FTLExitValue.cpp"
#include "ftl/FTLFail.cpp"
#include "ftl/FTLForOSREntryJITCode.cpp"
#include "ftl/FTLJITCode.cpp"
#include "ftl/FTLJITFinalizer.cpp"
#include "ftl/FTLLazySlowPath.cpp"
#include "ftl/FTLLink.cpp"
