set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CXX_FLAGS "/DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__")
set(VCPKG_C_FLAGS "/DWINAPI_FAMILY=WINAPI_FAMILY_APP /D__WRL_NO_DEFAULT_LIB__")

set(VCPKG_VISUAL_STUDIO_PATH "C:/Program Files/Microsoft Visual Studio/2022/Community")
set(VCPKG_PLATFORM_TOOLSET v143)
