#include "dom/TemplateContentDocumentFragment.cpp"
#include "dom/Text.cpp"
#include "dom/TextDecoder.cpp"
#include "dom/TextDecoderStreamDecoder.cpp"
#include "dom/TextEncoder.cpp"
#include "dom/TextEncoderStreamEncoder.cpp"
#include "dom/TextEvent.cpp"
#include "dom/TextNodeTraversal.cpp"
