#include "JSPayerErrorFields.cpp"
#include "JSPaymentAddress.cpp"
#include "JSPaymentComplete.cpp"
#include "JSPaymentCompleteDetails.cpp"
#include "JSPaymentCurrencyAmount.cpp"
#include "JSPaymentDetailsBase.cpp"
#include "JSPaymentDetailsInit.cpp"
#include "JSPaymentDetailsModifier.cpp"
