#include "JSGainNode.cpp"
#include "JSGainOptions.cpp"
#include "JSGamepad.cpp"
#include "JSGamepadButton.cpp"
#include "JSGamepadEffectParameters.cpp"
#include "JSGamepadEvent.cpp"
#include "JSGamepadHapticActuator.cpp"
#include "JSGamepadHapticEffectType.cpp"
