#include "platform/LocalizedStrings.cpp"
#include "platform/LogInitialization.cpp"
#include "platform/Logging.cpp"
#include "platform/LowPowerModeNotifier.cpp"
#include "platform/MIMETypeRegistry.cpp"
#include "platform/MainThreadSharedTimer.cpp"
#include "platform/MediaSamplesBlock.cpp"
#include "platform/MediaStrategy.cpp"
