#include "Modules/paymentrequest/PaymentRequest.cpp"
#include "Modules/paymentrequest/PaymentRequestUpdateEvent.cpp"
#include "Modules/paymentrequest/PaymentRequestUtilities.cpp"
#include "Modules/paymentrequest/PaymentResponse.cpp"
#include "Modules/permissions/MainThreadPermissionObserver.cpp"
#include "Modules/permissions/NavigatorPermissions.cpp"
#include "Modules/permissions/PermissionController.cpp"
#include "Modules/permissions/PermissionStatus.cpp"
