#include "Modules/geolocation/GeolocationController.cpp"
#include "Modules/geolocation/GeolocationCoordinates.cpp"
#include "Modules/geolocation/NavigatorGeolocation.cpp"
#include "Modules/highlight/AppHighlightRangeData.cpp"
#include "Modules/highlight/AppHighlightStorage.cpp"
#include "Modules/highlight/Highlight.cpp"
#include "Modules/highlight/HighlightRegistry.cpp"
#include "Modules/identity/CredentialRequestCoordinator.cpp"
