#include "dom/InternalObserverFirst.cpp"
#include "dom/InternalObserverForEach.cpp"
#include "dom/InternalObserverFromScript.cpp"
#include "dom/InternalObserverInspect.cpp"
#include "dom/InternalObserverLast.cpp"
#include "dom/InternalObserverMap.cpp"
#include "dom/InternalObserverReduce.cpp"
#include "dom/InternalObserverSome.cpp"
