#include "platform/graphics/Region.cpp"
#include "platform/graphics/RenderingMode.cpp"
#include "platform/graphics/RotationDirection.cpp"
#include "platform/graphics/ShadowBlur.cpp"
#include "platform/graphics/ShareableBitmap.cpp"
#include "platform/graphics/ShareableBitmapHandle.cpp"
#include "platform/graphics/SourceBrush.cpp"
#include "platform/graphics/SourceBufferPrivate.cpp"
