#include "dom/WindowOrWorkerGlobalScopeTrustedTypes.cpp"
#include "dom/XMLDocument.cpp"
#include "dom/messageports/MessagePortChannel.cpp"
#include "dom/messageports/MessagePortChannelProvider.cpp"
#include "dom/messageports/MessagePortChannelProviderImpl.cpp"
#include "dom/messageports/MessagePortChannelRegistry.cpp"
#include "dom/messageports/WorkerMessagePortChannelProvider.cpp"
