#include "platform/text/DateTimeFormat.cpp"
#include "platform/text/LocaleToScriptMapping.cpp"
#include "platform/text/PlatformLocale.cpp"
#include "platform/text/QuotedPrintable.cpp"
#include "platform/text/SegmentedString.cpp"
#include "platform/text/TextBoundaries.cpp"
#include "platform/text/TextFlags.cpp"
#include "platform/text/TextSpacing.cpp"
