#include "JSGPUTextureDescriptor.cpp"
#include "JSGPUTextureDimension.cpp"
#include "JSGPUTextureFormat.cpp"
#include "JSGPUTextureSampleType.cpp"
#include "JSGPUTextureUsage.cpp"
#include "JSGPUTextureView.cpp"
#include "JSGPUTextureViewDescriptor.cpp"
#include "JSGPUTextureViewDimension.cpp"
