#include "JSGPUCommandEncoderDescriptor.cpp"
#include "JSGPUCommandsMixin.cpp"
#include "JSGPUCompareFunction.cpp"
#include "JSGPUCompilationInfo.cpp"
#include "JSGPUCompilationMessage.cpp"
#include "JSGPUCompilationMessageType.cpp"
#include "JSGPUComputePassDescriptor.cpp"
#include "JSGPUComputePassEncoder.cpp"
