#include "platform/ThermalMitigationNotifier.cpp"
#include "platform/ThreadGlobalData.cpp"
#include "platform/ThreadTimers.cpp"
#include "platform/Timer.cpp"
#include "platform/TrackInfo.cpp"
#include "platform/UserActivity.cpp"
#include "platform/VideoDecoder.cpp"
#include "platform/VideoEncoder.cpp"
