#include "Modules/mediasource/MediaSourceInterfaceMainThread.cpp"
#include "Modules/mediasource/MediaSourceInterfaceWorker.cpp"
#include "Modules/mediasource/MediaSourceRegistry.cpp"
#include "Modules/mediasource/SampleMap.cpp"
#include "Modules/mediasource/SourceBuffer.cpp"
#include "Modules/mediasource/SourceBufferList.cpp"
#include "Modules/mediasource/VideoPlaybackQuality.cpp"
#include "Modules/mediastream/CanvasCaptureMediaStreamTrack.cpp"
