#include "JSServiceWorkerClientType.cpp"
#include "JSServiceWorkerClients.cpp"
#include "JSServiceWorkerContainer.cpp"
#include "JSServiceWorkerGlobalScope.cpp"
#include "JSServiceWorkerRegistration.cpp"
#include "JSServiceWorkerUpdateViaCache.cpp"
#include "JSServiceWorkerWindowClient.cpp"
#include "JSShadowRealmGlobalScope.cpp"
