#include "Modules/identity/DigitalCredential.cpp"
#include "Modules/identity/dummy/DummyCredentialRequestCoordinatorClient.cpp"
#include "Modules/indexeddb/IDBCursor.cpp"
#include "Modules/indexeddb/IDBCursorWithValue.cpp"
#include "Modules/indexeddb/IDBDatabase.cpp"
#include "Modules/indexeddb/IDBDatabaseIdentifier.cpp"
#include "Modules/indexeddb/IDBDatabaseNameAndVersionRequest.cpp"
#include "Modules/indexeddb/IDBFactory.cpp"
