#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class ComboBox;
                ref class TextBox;
                ref class ToggleSwitch;
                ref class Slider;
                ref class Button;
                ref class SwapChainPanel;
                ref class ProgressBar;
                ref class Border;
                ref class Image;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                ref class TranslateTransform;
            }
        }
    }
}

namespace Harness
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Media::TranslateTransform^ RootShift;
        private: ::Windows::UI::Xaml::Controls::Grid^ ActionMenu;
        private: ::Windows::UI::Xaml::Controls::Grid^ Drawer;
        private: ::Windows::UI::Xaml::Controls::Grid^ SettingsPage;
        private: ::Windows::UI::Xaml::Controls::Grid^ TabSwitcher;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ TabList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TabSwitcherTitle;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetSearchCombo;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetLangCombo;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SetHomeBox;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetUaSwitch;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SetUaCustomBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ SetZoomSlider;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetTabModeSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetGpuSwitch;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ VersionText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SetZoomLabel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ DrawerList;
        private: ::Windows::UI::Xaml::Controls::Button^ TabFav;
        private: ::Windows::UI::Xaml::Controls::Button^ TabHist;
        private: ::Windows::UI::Xaml::Controls::Button^ TabDl;
        private: ::Windows::UI::Xaml::Controls::Button^ ActionBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ GpuBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ UaBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ActUaLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ BackBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ FwdBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ActFavLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ TabsBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LockIcon;
        private: ::Windows::UI::Xaml::Controls::TextBox^ UrlBox;
        private: ::Windows::UI::Xaml::Controls::Button^ UrlActionBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TabCountText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TitleText;
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ GpuPanel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ ImeBox;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ Progress;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ScrollFab;
        private: ::Windows::UI::Xaml::Controls::Border^ FindBar;
        private: ::Windows::UI::Xaml::Controls::Border^ SuggestPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ SuggestList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FindCount;
        private: ::Windows::UI::Xaml::Controls::Button^ FindPrev;
        private: ::Windows::UI::Xaml::Controls::Button^ FindNext;
        private: ::Windows::UI::Xaml::Controls::Button^ FindClose;
        private: ::Windows::UI::Xaml::Controls::TextBox^ FindBox;
        private: ::Windows::UI::Xaml::Controls::Grid^ ContentArea;
        private: ::Windows::UI::Xaml::Controls::Image^ RenderImage;
    };
}

